
import type { BusinessProfile, AuditInputs, CompetitorData, V5AuditAnalysis, AuditReportData, ScoringFactor } from "../types";

export const calculateScore = (
  business: BusinessProfile,
  inputs: AuditInputs,
  competitors: CompetitorData[],
  internal: V5AuditAnalysis
): AuditReportData => {
  
  // V5: Score is generated by Gemini Intelligence
  const score = internal.local_visibility_confidence.score;

  // Adapter: Convert V5 Sections to List Factors for Compatibility with UI List View
  const factors: ScoringFactor[] = [];

  const addFactor = (id: string, name: string, score: number, max: number, reason: string, fix: string, cat: any) => {
    factors.push({
      id, name, score, maxScore: max,
      status: (score/max) < 0.5 ? 'critical' : (score/max) < 0.8 ? 'warning' : 'good',
      impact: max > 10 ? 'high' : 'medium',
      reason, fixAction: fix, category: cat
    });
  };

  // 1. Safety (15pts)
  const isSafe = internal.profile_safety_and_compliance.status === 'Safe';
  addFactor('v5_safe', 'Suspension Risk Check', isSafe ? 15 : 5, 15, 
    internal.profile_safety_and_compliance.explanation, 
    "Ensure name matches signage exactly.", 'eligibility');

  // 2. Categories (20pts)
  const catStatus = internal.category_and_relevance_analysis.primary_category.status;
  addFactor('v5_cat', 'Category Relevance', catStatus.includes('Strong') ? 20 : 10, 20, 
    internal.category_and_relevance_analysis.primary_category.explanation, 
    internal.category_and_relevance_analysis.primary_category.recommended_action, 'relevance');

  // 3. Reviews (25pts)
  const revStatus = internal.reviews_analysis.overall_status;
  const revScore = revStatus.includes('Strong') ? 25 : revStatus.includes('Competitive') ? 18 : 10;
  addFactor('v5_rev', 'Review Authority', revScore, 25, 
    internal.reviews_analysis.explanation, 
    `Target: ${internal.reviews_analysis.improvement_plan.monthly_target} new reviews/month.`, 'authority');

  // 4. Media (15pts)
  const mediaStatus = internal.photos_and_media_analysis.overall_status;
  addFactor('v5_media', 'Visual Trust Signals', mediaStatus.includes('Strong') ? 15 : 8, 15, 
    internal.photos_and_media_analysis.explanation, 
    internal.photos_and_media_analysis.recommended_actions.upload_frequency, 'conversion');

  // 5. Activity (15pts)
  addFactor('v5_act', 'Profile Engagement', 10, 15, 
    `Status: ${internal.profile_activity_and_engagement.status}`, 
    "Post weekly updates to improve signals.", 'conversion');

  // 6. Competitive (10pts)
  addFactor('v5_comp', 'Competitive Gap', 5, 10, 
    internal.competitive_benchmark.summary, 
    "Focus on closing the review gap.", 'authority');

  return { 
    business, 
    inputs, 
    overallScore: score, 
    factors, 
    geminiAnalysis: internal,
    competitors 
  };
};
